name: Build
on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.6
        with:
          version: 1.1.10
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/.cache/virtualenvs

      - name: Install dependencies
        run: |
          poetry install --no-interaction
      - name: Run dry-run
        if: github.event_name == 'pull_request'
        env:
          GIT_URL: "github.com"
          GIT_TOKEN: "${{ secrets.GIT_TOKEN }}"
        run: |
          poetry run archiver apply --dry-run ./data > output.txt
      - name: Danger JS Action
        env:
          GITHUB_TOKEN: "${{ secrets.GIT_TOKEN }}"
        if: github.event_name == 'pull_request'
        uses: danger/danger-js@9.1.8
      - name: Run apply for real
        if: github.ref == 'refs/heads/main'
        env:
          GIT_URL: "github.com"
          GIT_TOKEN: "${{ secrets.GIT_TOKEN }}"
        run: |
          poetry run archiver apply ./data
